In [14]:
import sys
#sys.path.insert(0, '/home/dlrc1/Documents/OSLSM-master/python/')
import caffe
from caffe.proto import caffe_pb2
from caffe import draw
from google.protobuf import text_format

In [3]:
import numpy as np
import tensorflow as tf
import tensorlayer as tl

In [3]:
net = caffe.Net('VGG_ILSVRC_16_layers_deploy.prototxt', 'VGG_ILSVRC_16_layers.caffemodel', caffe.TEST)

In [5]:
for blob in net.blobs:
    print(blob)
    
W = net.params['conv1_1'][0].data
b = net.params['conv1_1'][1].data

print('weights: ', W)
print('bias: ', b)

data
conv1_1
conv1_2
pool1
conv2_1
conv2_2
pool2
conv3_1
conv3_2
conv3_3
pool3
conv4_1
conv4_2
conv4_3
pool4
conv5_1
conv5_2
conv5_3
pool5
fc6
fc7
fc8
prob
weights:  [[[[  4.29470569e-01   3.73466998e-01  -6.13601133e-02]
   [  2.74769872e-01   3.86807770e-02  -3.67223352e-01]
   [ -5.74681684e-02  -2.62249678e-01  -3.50096762e-01]]

  [[  5.50379455e-01   4.40074533e-01  -8.13870355e-02]
   [  3.45739067e-01   4.06322069e-02  -4.53501314e-01]
   [ -5.86349145e-02  -3.30669671e-01  -4.85030204e-01]]

  [[  4.80015397e-01   4.08547401e-01  -6.51455522e-02]
   [  3.10477257e-01   5.02023660e-02  -4.03383434e-01]
   [ -5.08716851e-02  -2.85227507e-01  -4.18516338e-01]]]


 [[[  1.17273867e-01   1.62062630e-01   1.35693997e-01]
   [  1.48350164e-01   2.02298447e-01   1.61688417e-01]
   [  1.29344285e-01   1.71572417e-01   1.38710454e-01]]

  [[  2.08774377e-02   4.73412387e-02   4.18543853e-02]
   [  3.10493708e-02   6.58102185e-02   4.62574959e-02]
   [  3.16787697e-02   5.47101051e-02   

In [14]:
sess = tf.InteractiveSession()

/home/dlrc1/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [15]:
sess.close()

In [8]:
network = tf.keras.applications.VGG16()

553467904/553467096 [==============================] - 74s 0us/step


In [9]:
print(network)

In [12]:
npy = np.load('vgg16.npy', encoding='latin1')
params = []
for val in sorted(npy.item().items()):
    params.append(val[1]['weights'])
    params.append(val[1]['biases'])
tl.files.assign_params(sess, params, network)

AttributeError: 'Model' object has no attribute 'all_params'

In [11]:
all_var = tl.files.load_npy_to_any(name='vgg16.npy')

NameError: name 'tl' is not defined

In [10]:
conv1_weights = tf.get_variable('conv1_weights', initializer=data['conv1_1']['weights'])

conv1_biases = tf.get_variable('conv1_biases', initializer=data['conv1_1']['biases'])

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
conv_kernel_1 = tf.nn.conv2d(x, conv1_weights, strides=[1,2,2,1], padding='VALID', name='conv1')

bias_layer_1 = relu(tf.nn.bias_add(conv_kernel_1, conv1_biases))